# Generated by Django 5.2.7 on 2025-11-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Elective Type',
                'verbose_name_plural': 'Elective Types',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.IntegerField()),
                ('level', models.IntegerField()),
                ('prerequisites', models.CharField(blank=True, max_length=500)),
                ('corequisites', models.CharField(blank=True, max_length=500)),
                ('exclusions', models.CharField(blank=True, max_length=500)),
                ('mode', models.CharField(max_length=100)),
                ('assessment', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('study_guide_url', models.URLField(blank=True)),
                ('course_description_url', models.URLField(blank=True)),
                ('elective_types', models.ManyToManyField(related_name='courses', to='courses.electivetype')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StudentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('interest', models.CharField(choices=[('willing', 'Willing to Take'), ('not_willing', 'Not Willing to Take')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='courses.course')),
                ('elective_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.electivetype')),
            ],
            options={
                'verbose_name': 'Student Selection',
                'verbose_name_plural': 'Student Selections',
                'ordering': ['-created_at'],
                'unique_together': {('student_id', 'course', 'elective_type')},
            },
        ),
    ]
