# Generated by Django 5.2.7 on 2025-11-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentselection',
            name='interest',
            field=models.CharField(choices=[('not_willing', 'Not Willing to Take'), ('willing', 'Willing to Take'), ('prefer', 'Prefer to Take')], max_length=20),
        ),
    ]
